# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
        - v0.**
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          scope: super-protocol
          registry-url: 'https://registry.npmjs.org'
      - run: yarn --frozen-lock --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn run prepare --if-present
      - run: npm publish --beta --access public
        if: contains(github.ref_name, 'beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public
        if: ${{ contains(github.ref_name, 'beta') == false }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
